general:
  dataset_path: $npy_dataset
  cpu: True
  model_type: S2T
  dataset_size: 1

stage1:
  data: $data_bin
  task: speech_to_text
  path: $checkpoint
  config_yaml: config.yaml
  max_len_a: 2
  max_len_b: 500
