slurm_config: big
task_type: local_predict
dataset:
  split: test
  video_processor: YoucookVideoProcessor
  aligner: DSAligner
  bert_name: bert-base-uncased
  meta_processor: YoucookMetaProcessor
  test_path: data/youcook/youcook_val.pkl
  trainval_annotation: data/youcook/youcookii_annotations_trainval.json
  use_annotation_text: true
  vfeat_dir: data/feat/feat_youcook_s3d
  text_processor: TextProcessor
  num_iso_layer: 12
  max_video_len: 32
  max_len: 96
fairseq:
  dataset:
    batch_size: 256
    valid_subset: test
    num_workers: 2
  common_eval:
    path: runs/mtm/vlm/youcook/checkpoint_last.pt
model:
  model_cls: MMFusionJoint
  mm_encoder_cls: MMBertForJoint
  use_seg_emb: true
eval:
  save_path: runs/mtm/vlm/youcook/eval
metric: RetrievalMetric
predictor: RetrievalPredictor
