# this yaml cannot be run alone. you must use `how2.yaml`, `vtt.yaml` etc for training.
dataset:
  video_processor: VideoProcessor
  bert_name: bert-base-uncased
fairseq:
  common:
    tensorboard_logdir: run
    log_interval: 1000
  dataset:
    num_workers: 4
  optimization:
    lr: [ 0.00005 ]
    clip_norm: 2.0
    optimizer: adam
    adam_betas: (0.9, 0.98)
    lr_scheduler: polynomial_decay
    total_num_update: 1000000  # backward compatible on fairseq 1.0.0a0+af0389f for reproducibility.
    warmup_updates: 1000
    weight_decay: 0.0
    ddp_backend: no_c10d
