includes: projects/task/ft.yaml
dataset:
  meta_processor: YoucookMetaProcessor
  train_path: data/youcook/youcook_train.pkl
  val_path: data/youcook/youcook_val.pkl
  trainval_annotation: data/youcook/youcookii_annotations_trainval.json
  use_annotation_text: True
  video_processor: YoucookVideoProcessor
  vfeat_dir: data/feat/feat_youcook_s3d # /checkpoint/huxu/feat/youcook_vmz # /checkpoint/prarora/berniehuang/feat_youcook_vmz
  text_processor: TextProcessor
  aligner: DSAligner
  num_iso_layer: 12
model:
  model_cls: MMFusionJoint
  mm_encoder_cls: MMBertForJoint
loss:
  loss_cls: T2VContraLoss
fairseq:
  dataset:
    batch_size: 128
  optimization:
    max_epoch: 10
  checkpoint:
    save_dir: runs/task/youcook
 
